name: Python application
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest radon
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        radon cc -as ./*  | sed 's/\x1b\[[0-9;]*m//g' > radon.log
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
          author_name: uiandwe
          author_email: uiandwe@gmail.com
          message: "Auto updating my readme"
          add: "radon.log"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
