name: Python application
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest radon
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run radon
      run: |
        radon cc -as ./*  | sed 's/\x1b\[[0-9;]*m//g'
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
